const LEGALES={
  terminos:{title:'Términos y condiciones',body:`<h4>1. Aceptación de términos</h4><p>Al acceder y utilizar la plataforma Eventos PE (eventospe.com), usted acepta estar sujeto a estos términos y condiciones de uso. Si no está de acuerdo con alguno de estos términos, no utilice nuestros servicios.</p><h4>2. Descripción del servicio</h4><p>Eventos PE es una plataforma de venta de entradas para eventos en el Perú. Actuamos como intermediarios entre los organizadores de eventos y los compradores de entradas. No somos organizadores de los eventos.</p><h4>3. Registro y cuenta</h4><p>Para realizar compras debe crear una cuenta proporcionando información veraz y actualizada. Usted es responsable de mantener la confidencialidad de su contraseña y cuenta.</p><h4>4. Proceso de compra</h4><p>Al realizar una compra, usted acepta pagar el precio indicado más los cargos por servicio aplicables. Las entradas son digitales y se entregan por correo electrónico con código QR. Una vez confirmada la compra y emitida la entrada, esta es válida únicamente para el evento, fecha y zona indicados.</p><h4>5. Precios y pagos</h4><p>Los precios están expresados en Soles (PEN) e incluyen el IGV. Los pagos se procesan a través de Culqi, pasarela de pagos certificada PCI DSS. Aceptamos tarjetas Visa, Mastercard, American Express, Yape, Plin y transferencia bancaria.</p><h4>6. Propiedad intelectual</h4><p>Todo el contenido de la plataforma (textos, diseños, logotipos, código fuente) es propiedad de Eventos PE S.A.C. y está protegido por las leyes de propiedad intelectual del Perú.</p><h4>7. Limitación de responsabilidad</h4><p>Eventos PE no es responsable por cambios, cancelaciones o modificaciones que realicen los organizadores de eventos. En caso de cancelación por parte del organizador, se procederá con la devolución según nuestras políticas.</p><h4>8. Legislación aplicable</h4><p>Estos términos se rigen por las leyes de la República del Perú. Para cualquier controversia, las partes se someten a la jurisdicción de los tribunales de Lima.</p><p><strong>Última actualización: Mayo 2025</strong></p>`},
  privacidad:{title:'Política de privacidad',body:`<h4>1. Información que recopilamos</h4><p>Recopilamos datos personales necesarios para procesar sus compras: nombre completo, DNI, correo electrónico, número de teléfono y datos de pago (procesados por Culqi, nunca almacenados en nuestros servidores).</p><h4>2. Uso de la información</h4><p>Utilizamos su información para: procesar compras y entregar entradas, enviar confirmaciones y actualizaciones de eventos, mejorar nuestros servicios, cumplir con obligaciones legales y fiscales.</p><h4>3. Protección de datos</h4><p>Implementamos medidas de seguridad técnicas y organizativas: cifrado SSL 256-bit, procesamiento de pagos PCI DSS compliant a través de Culqi, acceso restringido a datos personales, copias de seguridad cifradas.</p><h4>4. Compartir información</h4><p>No vendemos ni compartimos su información personal con terceros, excepto: Culqi (procesamiento de pagos), organizadores de eventos (para validación de entradas), autoridades (cuando sea requerido por ley).</p><h4>5. Derechos del usuario</h4><p>Conforme a la Ley N° 29733, Ley de Protección de Datos Personales del Perú, usted tiene derecho a: acceder a sus datos, rectificar información incorrecta, solicitar la eliminación de sus datos, oponerse al tratamiento de sus datos.</p><h4>6. Cookies</h4><p>Utilizamos cookies técnicas y analíticas para mejorar su experiencia de navegación. Puede configurar su navegador para rechazar cookies.</p><p><strong>Última actualización: Mayo 2025</strong></p>`},
  devoluciones:{title:'Política de cambios y devoluciones',body:`<h4>1. Devoluciones por cancelación del evento</h4><p>Si un evento es cancelado por el organizador, se procederá con la devolución del 100% del valor de la entrada (incluido el cargo por servicio) dentro de los 15 días hábiles siguientes a la comunicación oficial de la cancelación.</p><h4>2. Cambio de fecha del evento</h4><p>Si el organizador cambia la fecha del evento, las entradas adquiridas serán válidas para la nueva fecha. Si no puede asistir en la nueva fecha, podrá solicitar la devolución dentro de los 7 días hábiles posteriores al anuncio del cambio.</p><h4>3. Devoluciones por error de compra</h4><p>Si realizó una compra por error (cantidad incorrecta, zona equivocada), puede solicitar la modificación o devolución dentro de las primeras 24 horas posteriores a la compra, siempre que el evento no se haya realizado.</p><h4>4. No se aceptan devoluciones en</h4><p>Cambio de opinión del comprador después de 24 horas, no asistencia al evento por motivos personales, entradas adquiridas en promoción o con descuento especial (salvo cancelación del evento).</p><h4>5. Proceso de devolución</h4><p>Para solicitar una devolución, envíe un correo a devoluciones@eventospe.com con: número de orden, motivo de la devolución, datos bancarios para la transferencia. La devolución se procesará al mismo medio de pago utilizado en la compra.</p><p><strong>Última actualización: Mayo 2025</strong></p>`},
  reclamaciones:{title:'Libro de reclamaciones',body:`<h4>Libro de reclamaciones virtual</h4><p>En cumplimiento del Código de Protección y Defensa del Consumidor (Ley N° 29571) y el Decreto Supremo N° 011-2011-PCM, ponemos a su disposición nuestro Libro de Reclamaciones virtual.</p><h4>Datos de la empresa</h4><p><strong>Razón social:</strong> Eventos PE S.A.C.<br><strong>RUC:</strong> 20612345678<br><strong>Dirección:</strong> Av. Javier Prado Este 4200, Santiago de Surco, Lima, Perú<br><strong>Teléfono:</strong> (01) 555-0100<br><strong>Email:</strong> reclamaciones@eventospe.com</p><h4>Para presentar un reclamo o queja</h4><p>Envíe un correo electrónico a <strong>reclamaciones@eventospe.com</strong> con los siguientes datos: nombre completo, DNI, teléfono de contacto, correo electrónico, número de pedido (si aplica), detalle del reclamo o queja, solicitud específica.</p><h4>Plazo de respuesta</h4><p>Nos comprometemos a responder su reclamo en un plazo máximo de 30 días calendario, conforme a la normativa vigente. Para quejas, el plazo es de 15 días hábiles.</p><h4>Diferencia entre queja y reclamo</h4><p><strong>Queja:</strong> Disconformidad con la atención recibida (no relacionada con el producto/servicio).<br><strong>Reclamo:</strong> Disconformidad con el producto o servicio adquirido.</p><h4>Autoridad competente</h4><p>INDECOPI — Instituto Nacional de Defensa de la Competencia y de la Protección de la Propiedad Intelectual.<br>Teléfono: (01) 224-7777<br>Web: www.indecopi.gob.pe</p><p><strong>Última actualización: Mayo 2025</strong></p>`},
  about:{title:'Sobre nosotros',body:`<h4>Eventos PE</h4><p>Somos la plataforma líder de venta de entradas online en el Perú. Desde 2023, conectamos a miles de personas con las mejores experiencias en conciertos, teatro, deportes, festivales y más.</p><h4>Nuestra misión</h4><p>Hacer que la compra de entradas sea simple, segura y accesible para todos los peruanos, ofreciendo la mejor experiencia digital con tecnología de primer nivel.</p><h4>Datos de contacto</h4><p><strong>Eventos PE S.A.C.</strong><br>RUC: 20612345678<br>Av. Javier Prado Este 4200, Santiago de Surco, Lima<br>Teléfono: (01) 555-0100<br>Email: contacto@eventospe.com</p>`},
  faq:{title:'Preguntas frecuentes',body:`<h4>¿Cómo recibo mis entradas?</h4><p>Las entradas se envían automáticamente a tu correo electrónico en formato digital con código QR. También puedes verlas en la sección "Mis Entradas" de tu cuenta.</p><h4>¿Qué métodos de pago aceptan?</h4><p>Aceptamos tarjetas Visa, Mastercard, American Express, Diners Club, Yape, Plin y transferencia bancaria (BCP, BBVA, Interbank). Todos los pagos son procesados por Culqi.</p><h4>¿Es seguro comprar aquí?</h4><p>Sí. Utilizamos Culqi como pasarela de pagos, que cuenta con certificación PCI DSS, encriptación SSL 256-bit y verificación 3D Secure. Tu información financiera nunca se almacena en nuestros servidores.</p><h4>¿Puedo devolver una entrada?</h4><p>Consulta nuestra política de cambios y devoluciones. En general, aceptamos devoluciones por cancelación del evento o dentro de las primeras 24 horas por error de compra.</p><h4>¿Cómo aplico un cupón de descuento?</h4><p>En el paso 2 del checkout (Resumen), encontrarás un campo para ingresar tu código de cupón. El descuento se aplicará automáticamente al total.</p>`},
  organizadores:{title:'Para organizadores',body:`<h4>Publica tu evento con nosotros</h4><p>Si eres organizador de eventos, te ofrecemos nuestra plataforma para vender entradas de forma profesional. Contáctanos en organizadores@eventospe.com para más información.</p>`},
  cookies:{title:'Política de cookies',body:`<h4>¿Qué son las cookies?</h4><p>Las cookies son pequeños archivos de texto que se almacenan en su dispositivo al visitar nuestra web. Nos ayudan a mejorar su experiencia de navegación.</p><h4>Cookies que utilizamos</h4><p><strong>Cookies técnicas:</strong> Necesarias para el funcionamiento de la plataforma (sesión, carrito de compras).<br><strong>Cookies analíticas:</strong> Nos ayudan a entender cómo usan los visitantes nuestra web (Google Analytics).<br><strong>Cookies de preferencias:</strong> Recuerdan sus preferencias (idioma, ubicación).</p><p>Puede configurar su navegador para rechazar todas las cookies o para que le avise cuando se envía una cookie.</p>`}
};
 
function openLegal(key){
  const data=LEGALES[key];
  if(!data)return;
  document.getElementById('legalTitle').textContent=data.title;
  document.getElementById('legalBody').innerHTML=data.body;
  document.getElementById('moLegal').classList.add('show');
}
function closeLegal(){document.getElementById('moLegal').classList.remove('show')}
document.getElementById('moLegal').addEventListener('click',function(e){if(e.target===this)closeLegal()});
 
let _t;
function showToast(msg){clearTimeout(_t);document.getElementById('toastMsg').textContent=msg;document.getElementById('toast').classList.add('show');_t=setTimeout(()=>document.getElementById('toast').classList.remove('show'),3200)}